version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: signglove-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=signglove
      - ESP32_IP=192.168.1.100
      - TTS_ENABLED=true
      - TTS_PROVIDER=gtts
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://frontend:80
    volumes:
      - ./backend:/app
      - backend_data:/app/data
      - backend_models:/app/models
      - backend_cache:/app/tts_cache
    depends_on:
      - mongo
    networks:
      - signnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn main:app --host 0.0.0.0 --port 8080

  mongo:
    image: mongo:7
    container_name: signglove-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=signglove
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
    networks:
      - signnet

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: signglove-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
      - mongo
    networks:
      - signnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: signglove-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - signnet

volumes:
  backend_data:
    driver: local
  backend_models:
    driver: local
  backend_cache:
    driver: local
  mongo_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  signnet:
    driver: bridge
